/* ============================================================
   1) Croma India – Product-wise Sales Report (FY 2021)
   ============================================================

   As a Product Owner, I want to generate a report of individual
   product sales (aggregated monthly at product level) for
   Croma India for FY 2021 so that I can track product performance
   and perform further product analytics in Excel.

   Output Fields:
   - Month
   - Product Name & Variant
   - Sold Quantity
   - Gross Price Per Item
   - Gross Price Total

   Requirements:
   - Data should be aggregated at monthly level.
   - Data should be filtered for FY 2021.
   - Customer should be Croma India only.
   ============================================================ */
   
SELECT *
FROM dim_customer
WHERE customer LIKE '%croma%';

SELECT 
    s.date,
    p.product_code,
    p.product,
    p.variant,
    s.sold_quantity,
    g.gross_price,
    ROUND(g.gross_price * s.sold_quantity, 2) AS total_gross_price
FROM gdb0041.fact_sales_monthly s
JOIN gdb0041.dim_product p
    ON s.product_code = p.product_code
JOIN gdb0041.fact_gross_price g
    ON s.product_code = g.product_code
   AND gdb0041.get_fiscal_year(s.date) = g.fiscal_year
WHERE s.customer_code = 90002002
  AND gdb0041.get_fiscal_year(s.date) = 2021;


/* ============================================================
   2) Gross Monthly Total Sales Report – Croma India
   ============================================================

   As a Product Owner, I need an aggregate monthly gross sales
   report for Croma India so that I can track total revenue
   generated by this customer and manage the business relationship.

   Output Fields:
   - Month
   - Total Gross Sales Amount (for that month)

   Requirements:
   - Aggregate gross sales at monthly level.
   - Filter data for Croma India only.
   ============================================================ */
   
SELECT  
    s.date,
    SUM(ROUND(g.gross_price * s.sold_quantity, 2)) AS total_gross_price
FROM gdb0041.fact_sales_monthly s
JOIN gdb0041.fact_gross_price g
    ON s.product_code = g.product_code
   AND gdb0041.get_fiscal_year(s.date) = g.fiscal_year
JOIN gdb0041.dim_customer c
    ON s.customer_code = c.customer_code
WHERE s.customer_code = 90002002
  AND c.market = 'India'
GROUP BY s.date;


/* ============================================================
   3) Yearly Gross Sales Report – Croma India
   ============================================================

   Generate a yearly sales report for Croma India to analyze
   annual revenue contribution.

   Output Fields:
   - Fiscal Year
   - Total Gross Sales Amount (for that year)

   Requirements:
   - Aggregate gross sales at fiscal year level.
   - Filter data for Croma India only.
   ============================================================ */
   
SELECT 
    gdb0041.get_fiscal_year(s.date) AS fis_year,
    SUM(ROUND(g.gross_price * s.sold_quantity, 2)) AS total_gross_price
FROM gdb0041.fact_sales_monthly s
JOIN gdb0041.fact_gross_price g
    ON s.product_code = g.product_code
   AND gdb0041.get_fiscal_year(s.date) = g.fiscal_year
JOIN gdb0041.dim_customer c
    ON s.customer_code = c.customer_code
WHERE s.customer_code = 90002002
  AND c.market = 'India'
GROUP BY fis_year;


/* ============================================================
   4) Stored Procedure – Monthly Gross Sales Report
   ============================================================

   As a Data Analyst, I want to create a reusable stored procedure
   that generates a monthly gross sales report so users with limited
   database access can run it without modifying the query.

   Parameters:
   - Customer Name
   - Fiscal Year (if required)

   Output Fields:
   - Month
   - Total Gross Sales (for that month from given customer)

   Requirements:
   - Logic should be dynamic and reusable.
   - Should eliminate need for manual query changes.
   ============================================================ */
   
DELIMITER $$

DROP PROCEDURE IF EXISTS gdb0041.get_monthly_gross_sales_for_customer;

CREATE PROCEDURE gdb0041.get_monthly_gross_sales_for_customer (
    IN in_cust_code INT
)
BEGIN

    SELECT  
        s.date AS month,
        SUM(ROUND(g.gross_price * s.sold_quantity, 2)) AS total_gross_sales
    FROM gdb0041.fact_sales_monthly s
    JOIN gdb0041.fact_gross_price g
        ON s.product_code = g.product_code
       AND gdb0041.get_fiscal_year(s.date) = g.fiscal_year
    JOIN gdb0041.dim_customer c
        ON s.customer_code = c.customer_code
    WHERE s.customer_code = in_cust_code
    GROUP BY s.date
    ORDER BY s.date;

END $$

DELIMITER ;
   
   
   /* ============================================================
   5) Stored Procedure – Market Badge Classification
   ============================================================

   Create a stored procedure that assigns a market badge based
   on total sold quantity.

   Input Parameters:
   - Market
   - Fiscal Year

   Business Logic:
   - If Total Sold Quantity > 5,000,000 → 'Gold'
   - Otherwise → 'Silver'

   Output:
   - Market Badge

   Requirements:
   - Aggregate total sold quantity at market level.
   - Evaluate badge based on defined threshold.
   - Reusable for any market and fiscal year.
   ============================================================ */

DELIMITER $$

DROP PROCEDURE IF EXISTS gdb0041.get_market_badge;

CREATE PROCEDURE gdb0041.get_market_badge (
    IN in_market VARCHAR(50),
    IN in_fiscal_year YEAR,
    OUT out_market_badge VARCHAR(10)
)
BEGIN

    DECLARE qty BIGINT DEFAULT 0;

    -- Set default market if empty
    IF in_market IS NULL OR in_market = '' THEN
        SET in_market = 'India';
    END IF;

    -- Get total sold quantity for the given market & fiscal year
    SELECT COALESCE(SUM(s.sold_quantity), 0)
    INTO qty
    FROM gdb0041.fact_sales_monthly s
    JOIN gdb0041.dim_customer c
        ON s.customer_code = c.customer_code
    WHERE c.market = in_market
      AND gdb0041.get_fiscal_year(s.date) = in_fiscal_year;

    -- Assign market badge
    IF qty > 5000000 THEN
        SET out_market_badge = 'Gold';
    ELSE
        SET out_market_badge = 'Silver';
    END IF;

END $$

DELIMITER ;

